# Этот файл экспортирует публичный API пакета check_receipts для использования в приложении.
from .core import (
    ERROR_CACHE,
    LAST_RUN_STATS,
    MAIN_FILE_CACHE,
    TITLE_CACHE,
    check_memory_limit,
    detect_file_type,
    extract_date_from_filename,
    fmt_dt,
    get_cached_xml,
    get_size_kb,
    get_xml_cache_stats,
    monitor_memory_usage_mb,
    now_s,
    parse_xml_direct,
)
from .domain import (
    ErrorReceiptProcessor,
    _find_existing_subdir,
    _resolve_input_dirs,
    detect_group_type,
    find_file_pairs_between_dirs,
    process_pairs_parallel_optimized,
    process_pairs_processpool,
    worker_process_main,
)
from .service import _add_client_info_ultrafast, main_with_date, save_errors_to_excel

__all__ = [
    "ERROR_CACHE",
    "LAST_RUN_STATS",
    "MAIN_FILE_CACHE",
    "TITLE_CACHE",
    "ErrorReceiptProcessor",
    "_add_client_info_ultrafast",
    "_find_existing_subdir",
    "_resolve_input_dirs",
    "check_memory_limit",
    "detect_file_type",
    "detect_group_type",
    "extract_date_from_filename",
    "find_file_pairs_between_dirs",
    "fmt_dt",
    "get_cached_xml",
    "get_size_kb",
    "get_xml_cache_stats",
    "main_with_date",
    "monitor_memory_usage_mb",
    "now_s",
    "parse_xml_direct",
    "process_pairs_parallel_optimized",
    "process_pairs_processpool",
    "save_errors_to_excel",
    "worker_process_main",
]
